using System.Collections.Generic;

// ****************************
// *  Scancodes for the binds *
// ****************************
namespace OcellusPlugin
{
    internal partial class EliteBinds
    {
        private readonly Dictionary<string, string> langMap = new Dictionary<string, string>
        {
            {"en-CA", "fr-CA" },
        };

        private readonly Dictionary<string, uint> keyMap = new Dictionary<string, uint>
        {
            {"en-US:Backspace", 8},
            {"en-US:Tab", 9},
            {"en-US:Enter", 13},
            {"en-US:Pause", 19},
            {"en-US:CapsLock", 20},
            {"en-US:Escape", 27},
            {"en-US:Space", 32},
            {"en-US:PageUp", 33},
            {"en-US:PageDown", 34},
            {"en-US:End", 35},
            {"en-US:Home", 36},
            {"en-US:LeftArrow", 37},
            {"en-US:UpArrow", 38},
            {"en-US:RightArrow", 39},
            {"en-US:DownArrow", 40},
            {"en-US:SYSRQ", 44},
            {"en-US:Insert", 45},
            {"en-US:Delete", 46},
            {"en-US:0", 48},
            {"en-US:1", 49},
            {"en-US:2", 50},
            {"en-US:3", 51},
            {"en-US:4", 52},
            {"en-US:5", 53},
            {"en-US:6", 54},
            {"en-US:7", 55},
            {"en-US:8", 56},
            {"en-US:9", 57},
            {"en-US:A", 65},
            {"en-US:B", 66},
            {"en-US:C", 67},
            {"en-US:D", 68},
            {"en-US:E", 69},
            {"en-US:F", 70},
            {"en-US:G", 71},
            {"en-US:H", 72},
            {"en-US:I", 73},
            {"en-US:J", 74},
            {"en-US:K", 75},
            {"en-US:L", 76},
            {"en-US:M", 77},
            {"en-US:N", 78},
            {"en-US:O", 79},
            {"en-US:P", 80},
            {"en-US:Q", 81},
            {"en-US:R", 82},
            {"en-US:S", 83},
            {"en-US:T", 84},
            {"en-US:U", 85},
            {"en-US:V", 86},
            {"en-US:W", 87},
            {"en-US:X", 88},
            {"en-US:Y", 89},
            {"en-US:Z", 90},
            {"en-US:LeftWindows", 91},
            {"en-US:RightWindows", 92},
            {"en-US:Apps", 93},
            {"en-US:Numpad_0", 96},
            {"en-US:Numpad_1", 97},
            {"en-US:Numpad_2", 98},
            {"en-US:Numpad_3", 99},
            {"en-US:Numpad_4", 100},
            {"en-US:Numpad_5", 101},
            {"en-US:Numpad_6", 102},
            {"en-US:Numpad_7", 103},
            {"en-US:Numpad_8", 104},
            {"en-US:Numpad_9", 105},
            {"en-US:Numpad_Multiply", 106},
            {"en-US:Numpad_Add", 107},
            {"en-US:Numpad_Subtract", 109},
            {"en-US:Numpad_Decimal", 110},
            {"en-US:Numpad_Divide", 111},
            {"en-US:F1", 112},
            {"en-US:F2", 113},
            {"en-US:F3", 114},
            {"en-US:F4", 115},
            {"en-US:F5", 116},
            {"en-US:F6", 117},
            {"en-US:F7", 118},
            {"en-US:F8", 119},
            {"en-US:F9", 120},
            {"en-US:F10", 121},
            {"en-US:F11", 122},
            {"en-US:F12", 123},
            {"en-US:NumLock", 144},
            {"en-US:ScrollLock", 145},
            {"en-US:Numpad_Enter", (13 | 0xE1000000)}, // hack
            {"en-US:LeftShift", 160},
            {"en-US:RightShift", 161},
            {"en-US:LeftControl", 162},
            {"en-US:RightControl", 163},
            {"en-US:LeftAlt", 164},
            {"en-US:RightAlt", 165},
            {"en-US:SemiColon", 186},
            {"en-US:Equals", 187},
            {"en-US:Comma", 188},
            {"en-US:Minus", 189},
            {"en-US:Period", 190},
            {"en-US:Slash", 191},
            {"en-US:Grave", 192}, // CHECK THIS
            {"en-US:LeftBracket", 219},
            {"en-US:BackSlash", 220},
            {"en-US:RightBracket", 221},
            {"en-US:Apostrophe", 222},

            {"fr-CA:é", 191},
            {"fr-CA:¸", 221},
            {"fr-CA:Hash", 192},
            {"fr-CA:Circumflex", 219},
            {"fr-CA:<", 220},

            {"en-GB:Grave", 223},
            {"en-GB:Hash", 222},
            {"en-GB:Apostrophe", 192},

        };
    }
}
