using System.Collections.Generic;

// ****************************
// *  Scancodes for the binds *
// ****************************
namespace OcellusPlugin
{
    internal partial class EliteBinds
    {
        private readonly Dictionary<string, uint> _keyMap = new Dictionary<string, uint>
        {
            {"Backspace", 8},
            {"Tab", 9},
            {"Enter", 13},
            {"Pause", 19},
            {"CapsLock", 20},
            {"Escape", 27},
            {"Space", 32},
            {"PageUp", 33},
            {"PageDown", 34},
            {"End", 35},
            {"Home", 36},
            {"LeftArrow", 37},
            {"UpArrow", 38},
            {"RightArrow", 39},
            {"DownArrow", 40},
            {"SYSRQ", 44},
            {"Insert", 45},
            {"Delete", 46},
            {"0", 48},
            {"1", 49},
            {"2", 50},
            {"3", 51},
            {"4", 52},
            {"5", 53},
            {"6", 54},
            {"7", 55},
            {"8", 56},
            {"9", 57},
            {"A", 65},
            {"B", 66},
            {"C", 67},
            {"D", 68},
            {"E", 69},
            {"F", 70},
            {"G", 71},
            {"H", 72},
            {"I", 73},
            {"J", 74},
            {"K", 75},
            {"L", 76},
            {"M", 77},
            {"N", 78},
            {"O", 79},
            {"P", 80},
            {"Q", 81},
            {"R", 82},
            {"S", 83},
            {"T", 84},
            {"U", 85},
            {"V", 86},
            {"W", 87},
            {"X", 88},
            {"Y", 89},
            {"Z", 90},
            {"LeftWindows", 91},
            {"RightWindows", 92},
            {"Apps", 93},
            {"Numpad_0", 96},
            {"Numpad_1", 97},
            {"Numpad_2", 98},
            {"Numpad_3", 99},
            {"Numpad_4", 100},
            {"Numpad_5", 101},
            {"Numpad_6", 102},
            {"Numpad_7", 103},
            {"Numpad_8", 104},
            {"Numpad_9", 105},
            {"Numpad_Multiply", 106},
            {"Numpad_Add", 107},
            {"Numpad_Subtract", 109},
            {"Numpad_Decimal", 110},
            {"Numpad_Divide", 111},
            {"F1", 112},
            {"F2", 113},
            {"F3", 114},
            {"F4", 115},
            {"F5", 116},
            {"F6", 117},
            {"F7", 118},
            {"F8", 119},
            {"F9", 120},
            {"F10", 121},
            {"F11", 122},
            {"F12", 123},
            {"NumLock", 144},
            {"ScrollLock", 145},
            {"Numpad_Enter", (13 | 0xE1000000)}, // hack
            {"LeftShift", 160},
            {"RightShift", 161},
            {"LeftControl", 162},
            {"RightControl", 163},
            {"LeftAlt", 164},
            {"RightAlt", 165},
            {"SemiColon", 186},
            {"Equals", 187},
            {"Comma", 188},
            {"Minus", 189},
            {"Period", 190},
            {"Slash", 191},
            {"Grave", 192},
            {"LeftBracket", 219},
            {"BackSlash", 220},
            {"RightBracket", 221},
            {"Apostrophe", 222},

            // Deal with en_ca

            {"é", 191 },
            {"¸", 221 },
            {"Hash", 192 },
            {"Circumflex", 219 }
        };
    }
}
